spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: cloud-file-storage
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}