spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: cloud-file-storage

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
